# Generated by Django 6.0.5 on 2026-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pickuppoint_product_supplier_order_orderproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт.', max_length=20),
        ),
    ]
