# Generated by Django 6.0.5 on 2026-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderproduct_count_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
