# Generated by Django 6.0.5 on 2026-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_order_data_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('сompleted', 'Завершен')], default='Новый', max_length=255),
        ),
    ]
